# Configuración de ActionCable
Rails.application.configure do
  config.action_cable.mount_path = '/cable'
  
  # Configuración de producción
  config.action_cable.url = ENV.fetch('ACTION_CABLE_URL', 'ws://localhost:3000/cable')
  config.action_cable.allowed_request_origins = ['http://localhost:3000', 'http://127.0.0.1:3000']
end
